# Generated by Django 4.2.6 on 2023-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Year', models.IntegerField(null=True)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='movie_info',
            name='Name',
            field=models.CharField(default='Default Name', max_length=250),
        ),
        migrations.AddField(
            model_name='movie_info',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
